import os
current_dir = os.getcwd()
folder_path = os.path.join(current_dir, 'logos')
CHOOSELOGO = os.path.join(folder_path, 'choose.png')
EMPLOYEESLOGO = os.path.join(folder_path, 'employees.jpg')
MONEYLOGO = os.path.join(folder_path, 'money.webp')
RELATIONLOGO = os.path.join(folder_path, 'relation.png')
SCHEDULELOGO = os.path.join(folder_path, 'schedule.png')
SETTINGSLOGO = os.path.join(folder_path, 'settings.jpg')
VINKJELOGO = os.path.join(folder_path, 'vinkje.png')