import os
current_dir = os.getcwd()
folder_path = os.path.join(current_dir, 'logos')
CHOOSELOGO = os.path.join(folder_path, 'choose-removebg-preview.png')
EMPLOYEESLOGO = os.path.join(folder_path, 'employees-removebg-preview.png')
MONEYLOGO = os.path.join(folder_path, 'money.webp')
RELATIONLOGO = os.path.join(folder_path, 'relation.png')
SCHEDULELOGO = os.path.join(folder_path, 'schedule-removebg-preview.png')
SETTINGSLOGO = os.path.join(folder_path, 'settings-removebg-preview.png')
VINKJELOGO = os.path.join(folder_path, 'vinkje-removebg-preview.png')